[package]
name = "example-foo"
version = "0.1.0"
edition = "2021"

[lib]
name = "example_foo"
path = "rust/lib.rs"

[[bin]]
name = "example-foo"
path = "rust/main.rs"

[build-dependencies]
cabal-foreign-library = { path = "../cabal-foreign-library" }
